#
# Karen - A highly efficient, multipurpose Discord bot written in Golang
#
# Copyright (C) 2015-2017 Lukas Breuer
# Copyright (C) 2017 Subliminal Apps
#
# This file is a part of the Karen Discord-Bot Project ("Karen").
#
# Karen is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Karen is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

version: "3"

# docker network create --subnet=172.254.254.0/24 userdef
networks:
  default:
    external:
      name: userdef

services:
  karen:
    image: sn0w/karen-runtime
    links:
      - rethinkdb
    volumes:
      - /srv/karen:/karen
      - /srv/karen-data:/srv/karen-data
    labels:
      - traefik.enable=true
      - traefik.port=1337
      - traefik.protocol=http
      - traefik.frontend.rule=Host:data.karen.vc

  rethinkdb:
    image: rethinkdb
    volumes:
      - /srv/rethinkdb:/data
    ports:
      - 127.0.0.1:8888:8080
      - 127.0.0.1:28015:28015
      - 127.0.0.1:29015:29015
