#!/usr/bin/env bash

set -e

FLAGS="$1"

CONDITIONALS=(
    "./src/modules/_modules.go"
    "./src/modules/_utils.go"
)

for f in "${CONDITIONALS[@]}"; do
    in="$f"
    out=${f//_}

    [[ -f ${out} ]] && rm ${out}
    ./pp.sh ${in} $FLAGS > ${out}
    goimports -w ${out}

    echo -e "//DO NOT EDIT THIS FILE UNDER ANY CIRCUMSTANCE\n//IT'S AUTOGENERATED AND WILL BE DELETED EACH TIME YOU COMPILE KAREN.\n\n$(cat ${out})" > ${out}
done
